In [35]:
import torch
print(torch.__version__)

2.11.0+cu128


In [36]:
if torch.cuda.is_available():
  print("gpytorch is using GPU")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("gpytorch is using CPU")

gpytorch is using GPU
Using GPU: Tesla T4


#Creating a Tensor

In [37]:
#using empty
a = torch.empty(2,3)
print(a)

tensor([[1.6420e-19, 0.0000e+00, 7.4109e-01],
        [4.2940e-01, 8.8544e-01, 5.7390e-01]])


In [38]:
#check type
type(a)

torch.Tensor

In [39]:
#using zeros
b = torch.zeros(2,3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [40]:
#using ones
c = torch.ones(2,3,3)
print(c)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


In [41]:
#using rand
c = torch.rand(2,3)
print(c)

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])


In [42]:
#useing seed
c = torch.rand(2,3)
#this gives different ranom value
#higher seed ensures reproducibility
torch.manual_seed(42)
d = torch.rand(2,3)
e = torch.rand(2,3)

print(c)
print(d)
print(e)

tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])


In [43]:
#using custom tensor
f = torch.tensor([[1,2,3],[4,5,6]])
print(f)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [44]:
#other ways to create tensor

#using arange
print("using arange ->", torch.arange(0,10,2))

#using linspace
print("using linspace ->", torch.linspace(0,10,10))

#using eye
print("using eye ->", torch.eye(5))

#using ones_like
print("using ones_like ->", torch.ones_like(f))

#using zeros_like
print("using zeros_like ->", torch.zeros_like(f))

#using empty_like
print("using empty_like ->", torch.empty_like(f))

#using rand_like
print("using rand_like ->", torch.rand_like(f, dtype = torch.float32))

#using full
print("using full ->", torch.full((3,3),5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using ones_like -> tensor([[1, 1, 1],
        [1, 1, 1]])
using zeros_like -> tensor([[0, 0, 0],
        [0, 0, 0]])
using empty_like -> tensor([[660490574,         0,         0],
        [        0,         0,         0]])
using rand_like -> tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#Tensor Data Type

In [45]:
#find data type
f.dtype

torch.int64

In [46]:
#assign data type
x = torch.tensor([1.0, 2.0, 3.0], dtype = torch.int32)
print(x)

tensor([1, 2, 3], dtype=torch.int32)


In [47]:
#Changing data type
x.to(torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


#Mathematical Operations

##1. Scaler Operation

In [49]:
x = torch.rand(2,2)
x

tensor([[0.2666, 0.6274],
        [0.2696, 0.4414]])

In [111]:
# addition
print(x-2)

#subtraction
print(x-2)

#multiplication
print(x*2)

#division
print(x/2)

#mod
print(x%2)

#power
print(x**2)

tensor([[-1.7334, -1.3726],
        [-1.7304, -1.5586]])
tensor([[-1.7334, -1.3726],
        [-1.7304, -1.5586]])
tensor([[0.5332, 1.2549],
        [0.5393, 0.8827]])
tensor([[0.1333, 0.3137],
        [0.1348, 0.2207]])
tensor([[0.2666, 0.6274],
        [0.2696, 0.4414]])
tensor([[0.0711, 0.3937],
        [0.0727, 0.1948]])


##2. Element wise Operation

In [52]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994]])
tensor([[0.5472, 0.0062, 0.9516],
        [0.0753, 0.8860, 0.5832]])


In [54]:
#add
print(a+b)

#sub
print(a-b)

#mul
print(a*b)

#div
print(a/b)

#mod
print(a%b)

#power
print(a**b)


tensor([[0.8441, 0.8378, 1.0569],
        [0.3448, 1.2448, 0.7826]])
tensor([[-0.2503,  0.8255, -0.8462],
        [ 0.1942, -0.5272, -0.3838]])
tensor([[0.1625, 0.0051, 0.1002],
        [0.0203, 0.3179, 0.1163]])
tensor([[5.4263e-01, 1.3500e+02, 1.1068e-01],
        [3.5806e+00, 4.0497e-01, 3.4184e-01]])
tensor([[2.9692e-01, 2.6345e-05, 1.0531e-01],
        [4.3697e-02, 3.5881e-01, 1.9936e-01]])
tensor([[0.5146, 0.9989, 0.1174],
        [0.9060, 0.4033, 0.3904]])


In [60]:
c = torch.tensor([1.2,-2.3,3.7,-4.5])

#abs
print(torch.abs(c))

#neg
print(torch.neg(c))

#sign
print(torch.sign(c))

#round
print(torch.round(c))

#ceil
print(torch.ceil(c))

#floor
print(torch.floor(c))

#clamp
print(torch.clamp(c, min = 1, max = 4))

tensor([1.2000, 2.3000, 3.7000, 4.5000])
tensor([-1.2000,  2.3000, -3.7000,  4.5000])
tensor([ 1., -1.,  1., -1.])
tensor([ 1., -2.,  4., -4.])
tensor([ 2., -2.,  4., -4.])
tensor([ 1., -3.,  3., -5.])
tensor([1.2000, 1.0000, 3.7000, 1.0000])


##3. Reduction Operation

In [67]:
e = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)
e

tensor([[3., 4., 3.],
        [7., 0., 9.]])

In [69]:
#sum
print(torch.sum(e))

#sum of columns
print(torch.sum(e, dim=0))

#sum of rows
print(torch.sum(e, dim=1))

tensor(26.)
tensor([10.,  4., 12.])
tensor([10., 16.])


In [70]:
#mean
print(torch.mean(e))

#mean of columns
print(torch.mean(e, dim=0))

#mean of rows
print(torch.mean(e, dim=1))

tensor(4.3333)
tensor([5., 2., 6.])
tensor([3.3333, 5.3333])


In [75]:
#median
print(torch.median(e))

#median of columns
print(torch.median(e, dim=0))

#median of rows
print(torch.median(e, dim=1))

tensor(3.)
torch.return_types.median(
values=tensor([3., 0., 3.]),
indices=tensor([0, 1, 0]))
torch.return_types.median(
values=tensor([3., 7.]),
indices=tensor([2, 0]))


In [77]:
#max
print(torch.max(e))

#max along column
print(torch.max(e,dim=0))

#max along row
print(torch.max(e,dim=1))


tensor(9.)
torch.return_types.max(
values=tensor([7., 4., 9.]),
indices=tensor([1, 0, 1]))
torch.return_types.max(
values=tensor([4., 9.]),
indices=tensor([1, 2]))


In [78]:
#min
print(torch.min(e))

#min along column
print(torch.min(e,dim=0))

#min along row
print(torch.min(e,dim=1))

tensor(0.)
torch.return_types.min(
values=tensor([3., 0., 3.]),
indices=tensor([0, 1, 0]))
torch.return_types.min(
values=tensor([3., 0.]),
indices=tensor([0, 1]))


In [83]:
#product
print(torch.prod(e))

#standard deviation
print(torch.std(e))

# variance
print(torch.var(e))

# argmax - >returns postion of maximum wala element
print(torch.argmax(e))

# argmax - >returns postion of minimum wala element
print(torch.argmin(e))

tensor(0.)
tensor(3.2042)
tensor(10.2667)
tensor(5)
tensor(4)


##4. Matrix Operation

In [102]:
f = torch.randint(size = (2,3), low = 1, high = 5, dtype = torch.float32)
g = torch.randint(size = (3,2), low = 1, high = 5, dtype = torch.float32)

print(f)
print(g)

tensor([[1., 4., 3.],
        [3., 1., 3.]])
tensor([[1., 2.],
        [3., 2.],
        [1., 4.]])


In [103]:
# matric multiplication
print(torch.matmul(f,g))

print(torch.matmul(g,f))

tensor([[16., 22.],
        [ 9., 20.]])
tensor([[ 7.,  6.,  9.],
        [ 9., 14., 15.],
        [13.,  8., 15.]])


In [104]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

#dot product
torch.dot(vector1,vector2)

tensor(11)

In [105]:
#transpose - > basically swaps two dimensions
# we are swaping dimension 0 with one
print(f)
print(torch.transpose(f, 0, 1))

i = torch.randint(size = (2,3,4), low = 0, high = 10, dtype = torch.float32)
print(i)
print(torch.transpose(i, 0, 1))

tensor([[1., 4., 3.],
        [3., 1., 3.]])
tensor([[1., 3.],
        [4., 1.],
        [3., 3.]])
tensor([[[6., 0., 3., 7.],
         [3., 8., 9., 8.],
         [2., 5., 5., 4.]],

        [[8., 1., 7., 9.],
         [2., 6., 8., 2.],
         [8., 2., 1., 0.]]])
tensor([[[6., 0., 3., 7.],
         [8., 1., 7., 9.]],

        [[3., 8., 9., 8.],
         [2., 6., 8., 2.]],

        [[2., 5., 5., 4.],
         [8., 2., 1., 0.]]])


In [106]:
#determinant
print(torch.matmul(g,f))
print(torch.det(torch.matmul(g,f)))

#inverse
print(torch.inverse(torch.matmul(g,f)))

tensor([[ 7.,  6.,  9.],
        [ 9., 14., 15.],
        [13.,  8., 15.]])
tensor(2.2888e-05)
tensor([[ 4395285.0000,  -879056.9375, -1758113.8750],
        [ 2930189.2500,  -586037.6875, -1172076.0000],
        [-5372014.5000,  1074402.7500,  2148806.0000]])


##5. Comparision Operation

In [108]:
i = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
j = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

print(i)
print(j)

# greater than
print(i>j)

# less than
print(i<j)

# equal to
print(i==j)

# not equal to
print(i!=j)

# greater than equal to
print(i>=j)

# less than equal to
print(i<=j)

tensor([[3., 1., 6.],
        [4., 6., 9.]])
tensor([[4., 8., 9.],
        [2., 5., 9.]])
tensor([[False, False, False],
        [ True,  True, False]])
tensor([[ True,  True,  True],
        [False, False, False]])
tensor([[False, False, False],
        [False, False,  True]])
tensor([[ True,  True,  True],
        [ True,  True, False]])
tensor([[False, False, False],
        [ True,  True,  True]])
tensor([[ True,  True,  True],
        [False, False,  True]])


##6. Special Functions

In [114]:
k = torch.randint(size=(2,3), low = 0, high = 10, dtype = torch.float32)
k

tensor([[4., 0., 1.],
        [0., 7., 0.]])

In [116]:
#sqrt
print(torch.sqrt(k))

#exp
print(torch.exp(k))

#log
print(torch.log(k))

#log10
print(torch.log10(k))

#log2
print(torch.log2(k))

#sin
print(torch.sin(k))

#cos
print(torch.cos(k))

#tan
print(torch.tan(k))

#sigmoid
print(torch.sigmoid(k))

#softmax
print(torch.softmax(k, dim = 0))

#relu
print(torch.relu(k))

tensor([[2.0000, 0.0000, 1.0000],
        [0.0000, 2.6458, 0.0000]])
tensor([[5.4598e+01, 1.0000e+00, 2.7183e+00],
        [1.0000e+00, 1.0966e+03, 1.0000e+00]])
tensor([[1.3863,   -inf, 0.0000],
        [  -inf, 1.9459,   -inf]])
tensor([[0.6021,   -inf, 0.0000],
        [  -inf, 0.8451,   -inf]])
tensor([[2.0000,   -inf, 0.0000],
        [  -inf, 2.8074,   -inf]])
tensor([[-0.7568,  0.0000,  0.8415],
        [ 0.0000,  0.6570,  0.0000]])
tensor([[-0.6536,  1.0000,  0.5403],
        [ 1.0000,  0.7539,  1.0000]])
tensor([[1.1578, 0.0000, 1.5574],
        [0.0000, 0.8714, 0.0000]])
tensor([[0.9820, 0.5000, 0.7311],
        [0.5000, 0.9991, 0.5000]])
tensor([[9.8201e-01, 9.1105e-04, 7.3106e-01],
        [1.7986e-02, 9.9909e-01, 2.6894e-01]])
tensor([[4., 0., 1.],
        [0., 7., 0.]])


# Inplace Operations

In [117]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)



tensor([[0.1764, 0.8649, 0.2726],
        [0.3998, 0.0026, 0.8346]])
tensor([[0.8788, 0.6822, 0.1514],
        [0.0065, 0.0939, 0.8729]])


In [118]:
# if we write m + n then it creates a ew tensor of same size
# this is a problem when we do this for large datasets as matrix
m+n

tensor([[1.0552, 1.5472, 0.4240],
        [0.4063, 0.0965, 1.7075]])

In [120]:
# to resolve this problem we sue inplace operations
m.add_(n)  # Now the sum is stored in m itself
print(m)


tensor([[1.0552, 1.5472, 0.4240],
        [0.4063, 0.0965, 1.7075]])


In [126]:
# Sigmoid example
m.sigmoid_()
m

tensor([[0.6600, 0.6609, 0.6584],
        [0.6584, 0.6575, 0.6611]])

# Copying a Tensor

In [127]:
a = torch.rand(2,3)
a

tensor([[0.7401, 0.9208, 0.7619],
        [0.6265, 0.4951, 0.1197]])

In [130]:
# Using simple Assignment operator
b=a
b

tensor([[0.7401, 0.9208, 0.7619],
        [0.6265, 0.4951, 0.1197]])

In [132]:
# But if I change something in a
a[0][0] = 1
print(a)
print(b)
# If original changes the copy also changes
# No copy is amde actually we make a new reference named as b

tensor([[1.0000, 0.9208, 0.7619],
        [0.6265, 0.4951, 0.1197]])
tensor([[1.0000, 0.9208, 0.7619],
        [0.6265, 0.4951, 0.1197]])


In [133]:
print(id(a))
print(id(b))

138932841147488
138932841147488


In [135]:
# we use clone for copying
b = a.clone()

a[0][0] = 10
print(a)
print(b)
print(id(a))
print(id(b))

tensor([[10.0000,  0.9208,  0.7619],
        [ 0.6265,  0.4951,  0.1197]])
tensor([[10.0000,  0.9208,  0.7619],
        [ 0.6265,  0.4951,  0.1197]])
138932841147488
138932842097200


# Tensor Operations on GPU

In [136]:
torch.cuda.is_available()

True

In [137]:
device = torch.device('cuda')

In [138]:
# Create a new tensor on GPU
torch.rand((2,3), device = device)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')

In [140]:
# Moving an existing tenosr  to GPU
a = torch.rand(2,3)
print(a)
b = a.to(device)
print(b)


tensor([[0.4089, 0.1481, 0.1733],
        [0.6659, 0.3514, 0.8087]])
tensor([[0.4089, 0.1481, 0.1733],
        [0.6659, 0.3514, 0.8087]], device='cuda:0')


In [141]:
b+5

tensor([[5.4089, 5.1481, 5.1733],
        [5.6659, 5.3514, 5.8087]], device='cuda:0')

#CPU vs GPU

In [143]:
import torch
import time

size = 10000

matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

#Measure Time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
end_time = time.time()
cpu_time = end_time - start_time

#Measure Time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize() #To ensure that all GPU operations are complete
end_time = time.time()
gpu_time = end_time - start_time

print(f'CPU Time: {cpu_time:.4f} seconds')
print(f'GPU Time: {gpu_time:.4f} seconds')

print("\nSpeed Up (CPU time/ GPU time):", cpu_time/gpu_time)


CPU Time: 15.6466 seconds
GPU Time: 0.5772 seconds

Speed Up (CPU time/ GPU time): 27.108468049740427


#Reshaping Tensors

In [144]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [145]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [147]:
# flatten
a.flatten()


tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [149]:
# permute
b = torch.rand(2,3,4)
print(b)
b.permute(2,0,1) # new shape is (4,2,3)

tensor([[[0.8969, 0.0301, 0.7877, 0.4157],
         [0.5091, 0.9837, 0.6442, 0.3903],
         [0.8759, 0.8276, 0.4708, 0.5587]],

        [[0.3420, 0.0917, 0.9406, 0.4332],
         [0.4028, 0.9066, 0.5453, 0.9750],
         [0.1213, 0.0988, 0.5528, 0.9711]]])


tensor([[[0.8969, 0.5091, 0.8759],
         [0.3420, 0.4028, 0.1213]],

        [[0.0301, 0.9837, 0.8276],
         [0.0917, 0.9066, 0.0988]],

        [[0.7877, 0.6442, 0.4708],
         [0.9406, 0.5453, 0.5528]],

        [[0.4157, 0.3903, 0.5587],
         [0.4332, 0.9750, 0.9711]]])

In [153]:
# unsqueeze
c = torch.rand(226, 226, 3) #image size
print(c.unsqueeze(0).shape) # adds a ne dimension at desired position
# helpful when making batch

# squeeze
d = torch.rand(1, 20)
print(d.squeeze(0).shape)


torch.Size([1, 226, 226, 3])
torch.Size([20])


#Numpy and PyTorch

In [155]:
import numpy as np

In [158]:
a = torch.tensor([1,2,3])
print(a)

# Convert tensor to Numpy
b = a.numpy()
print(b)
print(type(b))

# Convert Numpy to tensor
c = torch.from_numpy(b)
print(c)
print(type(c))

tensor([1, 2, 3])
[1 2 3]
<class 'numpy.ndarray'>
tensor([1, 2, 3])
<class 'torch.Tensor'>


In [ ]:
l